# Generated by Django 4.2.1 on 2024-04-03 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_position_alter_user_managers_user_rate_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date_interval', models.DateTimeField(blank=True)),
                ('end_date_interval', models.DateTimeField(blank=True)),
                ('amount', models.FloatField(blank=True)),
                ('status', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.payouts')),
            ],
        ),
    ]
