# Generated by Django 5.0.4 on 2024-04-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='employees_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
