# Generated by Django 5.0.4 on 2024-04-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_position_employees_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouts',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
