# Generated by Django 5.0.4 on 2024-04-27 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_payouts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='employees_count',
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.position'),
        ),
    ]
