# Generated by Django 5.0.4 on 2024-05-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_employee_code_alter_bonus_payout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
